### ISSUE TITLE
Support Bintracker

### ISSUE THREAD

**Issue by Gerirish** [HippoPlayer/HippoPlayer#173]
It's not urgent as the tracker is still under development, but I thought I'll already make you aware of https://bintracker.org

**Comment by emoon** [comment]
Looks like this tracker is written in Scheme. Hippoplayer mainly uses C/C++ so adding support for this tracker will likely be hard as a new player will have to be written.

**Comment by emoon** [comment]
Looked closer at the file format of the tracker, it's all scheme based so supporting this would mean re-implementing everything in C/C++ which is out of scope for HippoPlayer. If someone makes a player for the format that isn't in scheme this issue could be re-opened.
