### ISSUE TITLE
Add MP3 support

### ISSUE THREAD

**Issue by emoon** [HippoPlayer/HippoPlayer#181]

**Comment by Gerirish** [comment]
Which library do you intend to use for playback? Are you aware of https://www.mpg123.de ?

**Comment by emoon** [comment]
Not sure yet, there are tons of them so looking around. I know about mpg123 yes

**Comment by Gerirish** [comment]
There's also https://github.com/mackron/dr_libs/blob/master/dr_mp3.h (similar to dr_flac).

**Comment by emoon** [comment]
Yeah. I'm thinking about using that one, has a good licence and easy to use. It doesn't support ID3v2 tag parsing tho, but I could use another lib for that
