### ISSUE TITLE
Crash when deleting playlist entries

### ISSUE THREAD

**Issue by sagamusix** [HippoPlayer/HippoPlayer#187]
**Describe the bug**
HippoPlayer may crash under certain circumstances when deleting a file from the playlist.

**To Reproduce**
1. Add some files to playlist
2. Add a second playlist panel. Observe that playlist entries are now duplicated.
3. Close the newly added playlist panel again.
4. Try to remove a file from the remaining playlist panel. Hippo will crash.

**Comment by emoon** [comment]
Thanks!
