### ISSUE TITLE
Stereo separation

### ISSUE THREAD

**Issue by hrw** [HippoPlayer/HippoPlayer#192]
Some way to set stereo separation would be nice.

**Comment by emoon** [comment]
Yeah. This is coming in 0.2

![openmpt_settings](https://user-images.githubusercontent.com/350822/107782949-f7101a80-6d49-11eb-9410-f09c06530b9a.png)

**Comment by emoon** [comment]
This is now included in the 0.2 release. Notice this setting is currently global only, but it will be possible to tweak on a per file/directory/type/path/etc setting later on.
