### ISSUE TITLE
Support for David Whittaker

### ISSUE THREAD

**Issue by hsarcon** [HippoPlayer/HippoPlayer#203]
My wish is to play the good old games music :)

> .dw files are an audio file format (a so-called "exotic" module, i.e. a custom, non-tracker format) used in a number of Commodore Amiga games by the well-known composer David Whittaker.

There are lots of files available at
http://ftp.amigascne.org/mirrors/ftp.modland.com/pub/modules/David%20Whittaker/David%20Whittaker/

I think I remember that the original program could play this format, 

Thank YOU!

**Comment by emoon** [comment]
Thanks! These should actually work but it looks like hippo is crashing when trying to play these. I will take a look at this.

**Comment by Brog33** [comment]
I was also trying to play .dw files, but hippoplayer doesn't seem recognize them. The docs says that the UADE plugin should support it, but I cannot find the plugin in settings 🤔  

Created a thread in discussions about it (sorry if it's redundant)
https://github.com/HippoPlayer/HippoPlayer/discussions/212

**Comment by emoon** [comment]
See #212
