### ISSUE TITLE
App crashes on launch (MacOS Sonoma, Apple Silicon)

### ISSUE THREAD

**Issue by Brog33** [HippoPlayer/HippoPlayer#211]
**Describe the bug**
Crashes when I launch the app

**To Reproduce**
1. Doubleclick the app

**Expected behavior**
Not crash

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.2.1 (Apple Silicon)

**Additional context**
I know it is compiled for Intel, but I use Rosetta so it should work in theory.

**Comment by emoon** [comment]
Might be the same issue as this https://github.com/HippoPlayer/HippoPlayer/issues/205

**Comment by Brog33** [comment]
> Might be the same issue as this #205

I can provide crash logs if you need, or help testing it on Apple Silicon if you need it.

**Comment by emoon** [comment]
Did you try the approach in #205 to see if that works for you?

**Comment by emoon** [comment]
Great! I haven't had time to look into the issue as I'm very busy with other things :( but hopefully this workaround will do for now.

**Comment by Brog33** [comment]
Thanks a lot. I hope someone would carry on this project, it's really awesome! Been looking for a player like this for ages.

**Comment by emoon** [comment]
I plan to continue on the application in one form of the other.

**Comment by emoon** [comment]
Close as dupe of #205
