### ISSUE TITLE
Implement ASAP for supporting various 8-bit Atari formats

### ISSUE THREAD

**Issue by glennlunder** [HippoPlayer/HippoPlayer#40]
http://asap.sourceforge.net/

I see there are several other plugins already made using code from here, so it should be pretty easy to implement, I hope.

Gives us support for the following formats;

SAP (Slight Atari Player)
CMC (Chaos Music Composer)
CM3 (CMC "3/4")
CMR (CMC "Rzog")
CMS (Stereo Double CMC)
DMC (DoublePlay CMC)
DLT (Delta Music Composer)
FC (Future Composer)
MPT (Music ProTracker)
MPD (MPT DoublePlay)
RMT (Raster Music Tracker)
TMC, TM8 (Theta Music Composer 1.x)
TM2 (Theta Music Composer 2.x)

**Comment by emoon** [comment]
Implemented
