### ISSUE TITLE
Add support for Symphonie

### ISSUE THREAD

**Issue by emoon** [HippoPlayer/HippoPlayer#59]
http://us4.aminet.net/aminet/mus/play/SymphoniePlayer.zip (Java player that needs to be ported)

**Comment by sagamusix** [comment]
An OpenMPT contributor started working on implementing this format a while ago, but I guess he never finished it: https://bugs.openmpt.org/view.php?id=672
Maybe integrating it into libopenmpt rather than doing a stand-alone translation would be the way to go.

**Comment by emoon** [comment]
Yeah it really doesn't matter to me where it lives but a bunch of work to port the code for sure.

**Comment by sagamusix** [comment]
Symphonie support has just landed in libopenmpt! This will be part of libopenmpt 0.6.

**Comment by emoon** [comment]
Sweet!

**Comment by sagamusix** [comment]
I guess this can be closed now :)

**Comment by emoon** [comment]
Indeed. Thanks for the work on this one :)
