### ISSUE TITLE
adplug settings

### ISSUE THREAD

**Issue by ghost** [HippoPlayer/HippoPlayer#86]
Hi

Is it possible to add following settings for adplug?

- sample rate Hz setting for playback. 49716 Hz is best audio quality for adlib emulators since this is the sampling rate of a real yamaha chip.

- option to choose the adlib emulator used by adplug. See player audacious for example: https://audacious-media-player.org/

The 4 possible adlib emulators available in adplug are: 

* MAME (2003)
* Nuked OPL3 (2018)
* WoodyOPL (DOSBox, 2016)
* Ken Silverman (2001)

See attached screenshot of Audacious adplug settings.

![adplug](https://user-images.githubusercontent.com/65877513/87253841-9c92a100-c47e-11ea-8b46-528c3467fd49.jpg)

**Comment by emoon** [comment]
Yes, this is going to be possible when https://github.com/emoon/HippoPlayer/issues/50 is implemented

**Comment by emoon** [comment]
While sample rate hasn't been exposed yet, it's currently set to 49716 Hz at default (and then gets resampled depending on the output device)

**Comment by emoon** [comment]
Basic settings for adplug has been added in 0.2
