### ISSUE TITLE
feature request: BASS library

### ISSUE THREAD

**Issue by ghost** [HippoPlayer/HippoPlayer#92]
hi

not sure if this library is for all platforms and open source but it's according to me the best sounding tracker player out there.

http://www.un4seen.com/

Could it maybe be added in windows version?

**Comment by emoon** [comment]
It's not open source, but supported on many platforms so it might be possible to add it. When it comes to trackers I think libopenmpt is really good as well so I'm not really sure it's worth adding support for BASS but I will consider it

**Comment by jessicajonesunitedkingdom** [comment]
BASS sounds much better then openmpt and you can enable surround mode for tracker music

**Comment by emoon** [comment]
Alright. I will keep it on the list of things to implement.
